#!/usr/bin/env python3

import codecs

enc_flag = "cvpbPGS{arkg_gvzr_V'yy_gel_2_ebhaqf_bs_ebg13_nSkgmDJE}"
flag = codecs.decode(enc_flag, 'rot_13') # picoCTF{next_time_I'll_try_2_rounds_of_rot13_aFxtzQWR}

print(flag)